spring:
  application:
    name: greeting-microservice
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
greeting-microservice:
  greeting: "olá pessoal"
  defaultValue: "sou eu"
